# adventure_npc_data.py — D&D 5e 종족 기반 랜덤 NPC 풀
# 탐험 중 25% 확률로 등장하는 단기 NPC

ADVENTURE_NPCS = [
    {
        "id": "wandering_merchant_halfling",
        "name": "볼로",
        "race": "하프링",
        "type": "떠돌이 상인",
        "desc": "커다란 배낭을 진 쾌활한 하프링 상인. 무엇이든 가지고 있다고 주장한다.",
        "greeting": "\"어이, 여행자! 좋은 물건 있어! 오늘만 특별 할인이야!\"",
        "interaction": "trade",
        "trade_items": ["con_bread", "water", "gt_herb_01"],
        "trade_prices": {"con_bread": 15, "water": 10, "gt_herb_01": 20},
    },
    {
        "id": "wounded_elf_ranger",
        "name": "아에리스",
        "race": "엘프",
        "type": "부상당한 여행자",
        "desc": "나무에 기대어 앉아 있는 부상당한 우드 엘프 레인저. 어깨에서 피가 흐른다.",
        "greeting": "\"...도와줄 수 있겠나? 고블린에게 당했어.\"",
        "interaction": "help",
        "help_cost": {"item": "gt_herb_01", "count": 1},
        "help_reward": {"gold": 50, "exp": 30, "item": "feather"},
        "refuse_text": "\"...그래, 어쩔 수 없지.\" 아에리스가 고개를 돌린다.",
    },
    {
        "id": "suspicious_tiefling_mage",
        "name": "자리엘",
        "race": "티플링",
        "type": "수상한 마법사",
        "desc": "보랏빛 피부에 뿔이 달린 티플링이 의미심장한 미소를 짓고 있다.",
        "greeting": "\"잠깐, 재미있는 제안이 있어. 들어볼래?\"",
        "interaction": "gamble",
        "gamble_cost": 30,
        "gamble_win_chance": 0.5,
        "gamble_win_reward": {"gold": 100},
        "gamble_lose_text": "\"운이 없었네. 다음엔 이길 수 있을 거야.\" *킥킥 웃는다*",
    },
    {
        "id": "dwarf_blacksmith",
        "name": "토르딘",
        "race": "드워프",
        "type": "방랑 대장장이",
        "desc": "그을음 묻은 앞치마를 두른 건장한 드워프. 등에 모루를 지고 있다.",
        "greeting": "\"장비가 좀 낡았구만. 손봐줄까?\"",
        "interaction": "repair",
        "repair_cost": 25,
        "repair_effect": {"atk_buff": 3, "def_buff": 2, "duration": "1_battle"},
    },
    {
        "id": "githyanki_scout",
        "name": "라에즈엘의 정찰병",
        "race": "기스양키",
        "type": "적대적 정찰병",
        "desc": "은빛 갑옷을 입은 기스양키 전사가 경계의 눈으로 바라본다.",
        "greeting": "\"타르나크! 이곳은 네 영역이 아니다.\"",
        "interaction": "fight_or_flee",
        "fight_monster": {
            "name": "기스양키 정찰병",
            "id": "githyanki_scout_mob",
            "hp": 80,
            "attack": 20,
            "defense": 8,
            "exp": 50,
            "gold": (30, 60),
            "drops": [{"item": "silver_ore", "rate": 0.3}],
            "level": 10,
            "danger": "위험",
        },
    },
    {
        "id": "dragonborn_pilgrim",
        "name": "크라소스",
        "race": "드래곤본",
        "type": "순례자",
        "desc": "푸른 비늘의 드래곤본이 조용히 기도를 올리고 있다.",
        "greeting": "\"...바하무트의 축복이 함께하기를.\"",
        "interaction": "bless",
        "bless_effect": {"heal_hp_percent": 0.15, "heal_mp_percent": 0.10},
    },
    {
        "id": "gnome_tinkerer",
        "name": "피즈위크",
        "race": "노움",
        "type": "발명가",
        "desc": "온갖 기계 부품을 주렁주렁 달고 있는 작은 노움.",
        "greeting": "\"오! 모험가! 내 최신 발명품 좀 봐줄래?!\"",
        "interaction": "random_item",
        "possible_items": ["spider_web", "iron_ore", "coal", "feather", "mp_crystal"],
    },
    {
        "id": "halforc_mercenary",
        "name": "그로쉬",
        "race": "하프오크",
        "type": "용병",
        "desc": "거대한 도끼를 든 하프오크가 길 옆에 앉아 고기를 굽고 있다.",
        "greeting": "\"...같이 먹을래? 어차피 혼자 먹기엔 많아.\"",
        "interaction": "share_food",
        "share_effect": {"heal_hp": 20, "heal_en": 10},
    },
    {
        "id": "human_adventurer",
        "name": "보로미르",
        "race": "인간",
        "type": "방랑 모험가",
        "desc": "낡은 갑옷을 입은 중년의 인간 전사. 눈빛이 날카롭지만 인상은 좋다.",
        "greeting": "\"이 근처는 꽤 위험해. 조심해.\"",
        "interaction": "info",
        "info_text": "\"이 지역에서 조심할 몬스터는 특히 크기가 큰 놈들이야. 접근하기 전에 항상 주위를 살피는 게 중요해.\"",
        "info_reward": {"exp": 15},
    },
]

# NPC 등장 확률 (기본 25%)
NPC_ENCOUNTER_RATE = 0.25
