"""costume_data.py — 의장 아이템 DB, 간식 아이템 DB, 제작 레시피"""

# ─── 의장 아이템 ────────────────────────────────────────────────────────────
# Item type: "costume"; slot: toy|hat|outfit|shoes|accessory
COSTUME_ITEMS = {
    # ── 장난감 (toy) ──────────────────────────────────────────────────────
    "ct_toy_stick": {
        "name":        "나무 막대 장난감",
        "type":        "costume",
        "slot":        "toy",
        "grade":       "일반",
        "attack": 1,
        "description": "단순하지만 마음을 끄는 나무 막대 장난감.",
        "emoji":       "🪄",
        "price":       0,
    },
    "ct_toy_ball": {
        "name":        "털실 공",
        "type":        "costume",
        "slot":        "toy",
        "grade":       "일반",
        "defense": 1,
        "description": "폭신폭신한 털실로 만든 공.",
        "emoji":       "🧶",
        "price":       0,
    },
    "ct_toy_feather": {
        "name":        "깃털 장난감",
        "type":        "costume",
        "slot":        "toy",
        "grade":       "고급",
        "attack": 3,
        "defense": 1,
        "description": "알록달록한 깃털이 달린 장난감.",
        "emoji":       "🪶",
        "price":       0,
    },
    "ct_toy_magic_wand": {
        "name":        "반짝이 마법봉",
        "type":        "costume",
        "slot":        "toy",
        "grade":       "희귀",
        "attack": 6,
        "description": "반짝이는 별이 달린 마법봉. 기분이 좋아지는 기운이 흐른다.",
        "emoji":       "✨",
        "price":       0,
    },
    # ── 모자 (hat) ────────────────────────────────────────────────────────
    "ct_hat_ribbon": {
        "name":        "리본 머리띠",
        "type":        "costume",
        "slot":        "hat",
        "grade":       "일반",
        "defense": 2,
        "description": "귀여운 리본이 달린 머리띠.",
        "emoji":       "🎀",
        "price":       0,
    },
    "ct_hat_flower": {
        "name":        "꽃 화관",
        "type":        "costume",
        "slot":        "hat",
        "grade":       "일반",
        "defense": 2,
        "description": "들꽃으로 엮어 만든 작은 화관.",
        "emoji":       "🌸",
        "price":       0,
    },
    "ct_hat_crown": {
        "name":        "작은 왕관",
        "type":        "costume",
        "slot":        "hat",
        "grade":       "고급",
        "defense": 5,
        "description": "반짝이는 소재로 만든 미니 왕관.",
        "emoji":       "👑",
        "price":       0,
    },
    "ct_hat_witch": {
        "name":        "마녀 모자",
        "type":        "costume",
        "slot":        "hat",
        "grade":       "희귀",
        "defense": 8,
        "description": "뾰족한 마녀 모자. 신비로운 기운이 감돈다.",
        "emoji":       "🎩",
        "price":       0,
    },
    # ── 의상 (outfit) ─────────────────────────────────────────────────────
    "ct_outfit_apron": {
        "name":        "앞치마",
        "type":        "costume",
        "slot":        "outfit",
        "grade":       "일반",
        "defense": 3,
        "description": "깔끔한 체크 무늬 앞치마.",
        "emoji":       "👘",
        "price":       0,
    },
    "ct_outfit_maid": {
        "name":        "메이드 복장",
        "type":        "costume",
        "slot":        "outfit",
        "grade":       "고급",
        "defense": 7,
        "description": "단정한 메이드 유니폼.",
        "emoji":       "👗",
        "price":       0,
    },
    "ct_outfit_noble": {
        "name":        "귀족 드레스",
        "type":        "costume",
        "slot":        "outfit",
        "grade":       "희귀",
        "defense": 13,
        "description": "화려한 자수가 놓인 귀족 스타일 드레스.",
        "emoji":       "🥻",
        "price":       0,
    },
    "ct_outfit_knight": {
        "name":        "기사단 예복",
        "type":        "costume",
        "slot":        "outfit",
        "grade":       "전설",
        "defense": 22,
        "attack": 5,
        "description": "발더스게이트 기사단의 화려한 예복.",
        "emoji":       "⚔️",
        "price":       0,
    },
    # ── 신발 (shoes) ──────────────────────────────────────────────────────
    "ct_shoes_slippers": {
        "name":        "폭신 슬리퍼",
        "type":        "costume",
        "slot":        "shoes",
        "grade":       "일반",
        "defense": 1,
        "description": "발이 편안한 폭신한 슬리퍼.",
        "emoji":       "🩴",
        "price":       0,
    },
    "ct_shoes_boots": {
        "name":        "리본 부츠",
        "type":        "costume",
        "slot":        "shoes",
        "grade":       "고급",
        "defense": 4,
        "description": "발목에 리본이 달린 귀여운 부츠.",
        "emoji":       "👢",
        "price":       0,
    },
    "ct_shoes_heels": {
        "name":        "구두",
        "type":        "costume",
        "slot":        "shoes",
        "grade":       "희귀",
        "defense": 7,
        "description": "우아한 느낌의 귀족 구두.",
        "emoji":       "👠",
        "price":       0,
    },
    "ct_shoes_magic": {
        "name":        "마법 구두",
        "type":        "costume",
        "slot":        "shoes",
        "grade":       "전설",
        "defense": 12,
        "attack": 3,
        "description": "마법이 깃들어 어디서든 발이 편안한 구두.",
        "emoji":       "✨",
        "price":       0,
    },
    # ── 악세사리 (accessory) ──────────────────────────────────────────────
    "ct_acc_bracelet": {
        "name":        "비즈 팔찌",
        "type":        "costume",
        "slot":        "accessory",
        "grade":       "일반",
        "defense": 1,
        "description": "알록달록한 비즈로 만든 팔찌.",
        "emoji":       "📿",
        "price":       0,
    },
    "ct_acc_necklace": {
        "name":        "꽃잎 목걸이",
        "type":        "costume",
        "slot":        "accessory",
        "grade":       "고급",
        "defense": 3,
        "description": "작은 꽃잎 펜던트가 달린 목걸이.",
        "emoji":       "💐",
        "price":       0,
    },
    "ct_acc_brooch": {
        "name":        "별 브로치",
        "type":        "costume",
        "slot":        "accessory",
        "grade":       "희귀",
        "defense": 5,
        "attack": 2,
        "description": "반짝이는 별 모양 브로치.",
        "emoji":       "⭐",
        "price":       0,
    },
    "ct_acc_crown_jewel": {
        "name":        "왕관 보석",
        "type":        "costume",
        "slot":        "accessory",
        "grade":       "전설",
        "defense": 10,
        "attack": 5,
        "description": "왕가의 보석. 착용자에게 위엄을 부여한다.",
        "emoji":       "💎",
        "price":       0,
    },
}



# ─── 의장별 연출 문장 ──────────────────────────────────────────────────────
# equip: 막 장착했을 때 / observe: 평소 관찰에서 보이는 모습 / craft: 완성 직후
COSTUME_FLAVOR = {
    "ct_toy_stick": {
        "equip": "나무 막대를 건네자 츄라이더가 앞다리로 몇 번 굴려 본 뒤 손에 쥡니다. 단순한 물건인데도 꽤 마음에 든 눈치입니다.",
        "observe": "나무 막대를 앞다리 사이에 끼워 두고 틈날 때마다 바닥을 톡톡 두드립니다.",
        "craft": "매끈하게 다듬은 막대를 완성하자 츄라이더가 끝부분을 유심히 살펴봅니다.",
    },
    "ct_toy_ball": {
        "equip": "털실 공을 놓자 여덟 다리 중 하나가 먼저 툭 건드립니다. 공이 굴러가자 태연한 얼굴로 바로 뒤를 따라갑니다.",
        "observe": "털실 공이 보금자리 한가운데 굴러다닙니다. 실 끝 하나는 어느새 앞다리에 감겨 있습니다.",
        "craft": "둥글게 감은 털실 공이 완성되자 츄라이더가 손끝으로 눌러 폭신함을 확인합니다.",
    },
    "ct_toy_feather": {
        "equip": "깃털을 흔들자 드로우 상체는 가만히 있는데 앞다리 두 개가 동시에 반응합니다. 잠시 뒤에는 대놓고 쫓아다닙니다.",
        "observe": "깃털 끝이 움직일 때마다 앞다리 하나가 반사적으로 따라갑니다.",
        "craft": "깃털을 단단히 묶어 장난감을 완성하자 츄라이더의 시선이 끝에서 떨어지지 않습니다.",
    },
    "ct_toy_magic_wand": {
        "equip": "마법봉 끝의 반짝임이 켜지자 츄라이더가 얼굴 가까이 가져가 살핍니다. 빛이 움직일 때마다 여덟 다리가 아주 조금씩 따라 움직입니다.",
        "observe": "반짝이 마법봉을 손에 쥔 채 가끔 허공에 작은 원을 그립니다. 본인은 아무 의미 없다는 표정입니다.",
        "craft": "별 장식에 마법 가루가 스며들며 희미한 빛이 맺힙니다. 츄라이더가 바로 손을 내밉니다.",
    },
    "ct_hat_ribbon": {
        "equip": "리본 머리띠를 씌우자 잠시 손으로 리본을 만져 봅니다. 벗지는 않습니다.",
        "observe": "흰 머리카락 사이의 리본이 움직일 때마다 살짝 흔들립니다. 의외로 꽤 얌전히 쓰고 있습니다.",
        "craft": "리본을 묶어 머리띠를 마무리하자 츄라이더가 거울 대신 금속 조각에 비친 모습을 힐끗 봅니다.",
    },
    "ct_hat_flower": {
        "equip": "꽃 화관을 얹자 향을 확인하듯 고개를 조금 숙입니다. 꽃잎이 머리카락 사이에 걸립니다.",
        "observe": "화관의 작은 꽃잎 하나가 흰 머리카락 위에 떨어져도 그대로 두고 있습니다.",
        "craft": "작은 꽃들을 엮어 화관을 완성하자 츄라이더가 꽃잎을 손끝으로 조심스럽게 눌러 봅니다.",
    },
    "ct_hat_crown": {
        "equip": "작은 왕관을 씌우자 자세가 괜히 한층 꼿꼿해집니다. 표정은 평소와 똑같습니다.",
        "observe": "왕관이 기울 때마다 손으로 다시 정중앙에 맞춥니다. 생각보다 꽤 신경 쓰고 있습니다.",
        "craft": "반짝이 단추를 박아 왕관을 완성하자 츄라이더가 한참 들여다보다 머리를 내밉니다.",
    },
    "ct_hat_witch": {
        "equip": "뾰족한 모자를 눌러 씌우자 챙 아래로 눈만 보입니다. 잠시 뒤 손으로 각도를 고쳐 씁니다.",
        "observe": "마녀 모자 챙 아래에서 눈만 가늘게 빛납니다. 움직일 때마다 모자 끝이 느리게 흔들립니다.",
        "craft": "마법 가루가 실 사이에 스며들며 모자 끝이 아주 희미하게 반짝입니다.",
    },
    "ct_outfit_apron": {
        "equip": "앞치마 끈을 묶는 동안 얌전히 서 있습니다. 끝나자 앞섶을 손으로 펴서 모양을 확인합니다.",
        "observe": "앞치마 주머니 안에 언제 넣었는지 작은 단추와 실 조각이 들어 있습니다.",
        "craft": "체크 천과 리본을 정리해 앞치마를 완성하자 츄라이더가 주머니부터 확인합니다.",
    },
    "ct_outfit_maid": {
        "equip": "메이드 복장을 입히자 흰 머리카락과 검은 천이 또렷하게 대비됩니다. 츄라이더는 소매 끝을 정리하고 가만히 섭니다.",
        "observe": "메이드 복장 자락이 거미 복부 위로 가지런히 내려와 있습니다. 앞다리로 구김을 자꾸 펴고 있습니다.",
        "craft": "단추와 리본을 맞춰 복장을 완성하자 츄라이더가 옷깃을 손끝으로 정돈합니다.",
    },
    "ct_outfit_noble": {
        "equip": "귀족 드레스를 입히자 한동안 움직임이 조심스러워집니다. 곧 여덟 다리까지 우아하게 모아 앉아 봅니다.",
        "observe": "화려한 자락이 거미 복부 둘레로 퍼져 있습니다. 움직일 때마다 자수가 빛을 조금씩 받습니다.",
        "craft": "비단과 장식을 이어 드레스를 완성하자 츄라이더가 드레스 끝을 들어 올려 한참 살펴봅니다.",
    },
    "ct_outfit_knight": {
        "equip": "기사단 예복을 입히자 어깨가 눈에 띄게 펴집니다. 앞다리 두 개까지 괜히 반듯하게 정렬됩니다.",
        "observe": "기사단 예복 차림으로 책장 뒤에 웅크리고 있으니 묘하게 위엄과 은신이 동시에 느껴집니다.",
        "craft": "금속 장식과 천을 맞춰 예복을 완성하자 츄라이더가 꽤 진지한 얼굴로 옷깃을 만집니다.",
    },
    "ct_shoes_slippers": {
        "equip": "폭신 슬리퍼를 신겨 주자 처음에는 발끝을 몇 번 털어 보다가 곧 편하게 체중을 싣습니다.",
        "observe": "슬리퍼를 신은 다리들이 바닥을 디딜 때마다 평소보다 소리가 훨씬 작습니다.",
        "craft": "폭신한 안감을 넣어 슬리퍼를 완성하자 츄라이더가 손으로 꾹 눌러 봅니다.",
    },
    "ct_shoes_boots": {
        "equip": "리본 부츠를 신기자 다리 끝을 하나씩 들어 리본을 확인합니다. 걸을 때마다 작은 매듭이 흔들립니다.",
        "observe": "여덟 다리의 리본이 제각기 조금씩 다른 방향을 보고 있습니다. 본인은 전혀 신경 쓰지 않습니다.",
        "craft": "가죽과 리본을 맞춰 부츠를 완성하자 츄라이더가 다리 하나를 먼저 내밉니다.",
    },
    "ct_shoes_heels": {
        "equip": "구두를 신긴 첫 몇 걸음은 유난히 조심스럽습니다. 곧 균형을 잡고 생각보다 자연스럽게 걷습니다.",
        "observe": "구두 굽이 바닥에 닿을 때마다 또각거리는 소리가 규칙적으로 이어집니다.",
        "craft": "매끈하게 마감한 구두를 내려놓자 츄라이더가 각도를 바꿔 가며 반짝임을 확인합니다.",
    },
    "ct_shoes_magic": {
        "equip": "마법 구두를 신기자 다리 끝이 바닥에서 아주 가볍게 떠오르는 듯합니다. 츄라이더가 몇 걸음 시험해 보고 고개를 끄덕입니다.",
        "observe": "마법 구두를 신은 다리가 움직일 때마다 발끝에 희미한 빛이 짧게 남습니다.",
        "craft": "마법 가루가 밑창에 스며들며 희미한 빛이 번집니다. 완성된 구두가 손 안에서 가볍게 느껴집니다.",
    },
    "ct_acc_bracelet": {
        "equip": "비즈 팔찌를 채워 주자 손목을 돌려 색을 하나씩 확인합니다. 마음에 드는 비즈 하나를 손톱으로 톡 건드립니다.",
        "observe": "손을 움직일 때마다 비즈가 작게 부딪혀 맑은 소리가 납니다.",
        "craft": "색이 다른 비즈를 꿰어 팔찌를 완성하자 츄라이더가 가장 반짝이는 알을 바로 찾아냅니다.",
    },
    "ct_acc_necklace": {
        "equip": "꽃잎 목걸이를 걸어 주자 펜던트를 손바닥에 올려 한참 들여다봅니다.",
        "observe": "작은 꽃잎 펜던트가 드로우의 흰 피부 위에서 가볍게 흔들립니다.",
        "craft": "꽃잎 장식을 매달아 목걸이를 완성하자 츄라이더가 끈의 길이를 직접 맞춰 봅니다.",
    },
    "ct_acc_brooch": {
        "equip": "별 브로치를 달자 몸을 조금 비틀어 반짝임을 확인합니다. 위치가 마음에 들지 않는지 한 번 직접 고칩니다.",
        "observe": "별 브로치가 빛을 받을 때마다 츄라이더가 아주 잠깐씩 내려다봅니다.",
        "craft": "단추와 금속 장식을 조합해 별 모양을 완성하자 츄라이더가 손끝으로 별 끝을 따라 그립니다.",
    },
    "ct_acc_crown_jewel": {
        "equip": "왕관 보석을 달자 주위가 아주 미세하게 밝아집니다. 츄라이더도 잠시 말없이 빛을 바라봅니다.",
        "observe": "왕관 보석은 움직이지 않아도 은은하게 빛납니다. 보금자리의 실과 작은 물건들까지 같이 반짝입니다.",
        "craft": "여러 장식을 한데 고정하자 보석에서 깊은 빛이 맺힙니다. 츄라이더가 평소보다 훨씬 조심스럽게 받아 듭니다.",
    },
}

# ─── 간식 아이템 ────────────────────────────────────────────────────────────
SNACK_ITEMS = {
    "snack_cookie": {
        "name":        "수제 쿠키",
        "type":        "snack",
        "grade":       "일반",
        "effect":      {"condition": 10, "fatigue": -5},
        "description": "달콤한 수제 쿠키. 기분을 조금 좋게 해줌미댜.",
        "emoji":       "🍪",
        "price":       0,
    },
    "snack_cake": {
        "name":        "작은 케이크",
        "type":        "snack",
        "grade":       "고급",
        "effect":      {"condition": 20, "stability": 5, "fatigue": -8},
        "description": "예쁘게 장식된 작은 케이크.",
        "emoji":       "🎂",
        "price":       0,
    },
    "snack_honey_bread": {
        "name":        "꿀빵",
        "type":        "snack",
        "grade":       "일반",
        "effect":      {"condition": 12, "fatigue": -6},
        "description": "달콤한 꿀을 듬뿍 바른 빵.",
        "emoji":       "🍞",
        "price":       0,
    },
    "snack_fruit_tart": {
        "name":        "과일 타르트",
        "type":        "snack",
        "grade":       "고급",
        "effect":      {"condition": 18, "stability": 8, "fatigue": -5},
        "description": "신선한 과일로 만든 타르트.",
        "emoji":       "🫐",
        "price":       0,
    },
    "snack_chocolate": {
        "name":        "초콜릿",
        "type":        "snack",
        "grade":       "일반",
        "effect":      {"condition": 8, "stability": 5},
        "description": "달콤쌉싸름한 초콜릿.",
        "emoji":       "🍫",
        "price":       0,
    },
    "snack_milk_candy": {
        "name":        "밀크 캔디",
        "type":        "snack",
        "grade":       "일반",
        "effect":      {"condition": 7, "fatigue": -3},
        "description": "우유로 만든 부드러운 사탕.",
        "emoji":       "🍬",
        "price":       0,
    },
    "snack_magic_macaron": {
        "name":        "마법 마카롱",
        "type":        "snack",
        "grade":       "희귀",
        "effect":      {"condition": 30, "stability": 15, "fatigue": -15},
        "description": "마법 재료로 만든 특제 마카롱. 몸과 마음이 회복된다.",
        "emoji":       "🧁",
        "price":       0,
    },
    "snack_popcorn": {
        "name":        "팝콘",
        "type":        "snack",
        "grade":       "일반",
        "effect":      {"condition": 5, "fatigue": -2},
        "description": "바삭바삭한 팝콘.",
        "emoji":       "🍿",
        "price":       0,
    },
    "snack_pudding": {
        "name":        "푸딩",
        "type":        "snack",
        "grade":       "고급",
        "effect":      {"condition": 15, "stability": 10, "fatigue": -7},
        "description": "흔들흔들 맛있는 푸딩.",
        "emoji":       "🍮",
        "price":       0,
    },
    "snack_legendary_feast": {
        "name":        "전설의 만찬",
        "type":        "snack",
        "grade":       "전설",
        "effect":      {"condition": 50, "stability": 25, "fatigue": -30},
        "description": "발더스게이트의 최고 요리사가 만든 전설적인 요리.",
        "emoji":       "🍽️",
        "price":       0,
    },
}

# ─── 간식 제작 레시피 ────────────────────────────────────────────────────────
SNACK_RECIPES = {
    "snack_cookie": {
        "name":         "수제 쿠키 제작",
        "materials":    {"mat_wheat": 2, "mat_sugar": 1},
        "result_count": 2,
        "desc":         "밀 2개 + 설탕 1개 → 수제 쿠키 x2",
    },
    "snack_cake": {
        "name":         "작은 케이크 제작",
        "materials":    {"mat_wheat": 3, "mat_sugar": 2, "mat_butter": 1},
        "result_count": 1,
        "desc":         "밀 3개 + 설탕 2개 + 버터 1개 → 작은 케이크",
    },
    "snack_honey_bread": {
        "name":         "꿀빵 제작",
        "materials":    {"mat_wheat": 2, "mat_honey": 1},
        "result_count": 2,
        "desc":         "밀 2개 + 꿀 1개 → 꿀빵 x2",
    },
    "snack_fruit_tart": {
        "name":         "과일 타르트 제작",
        "materials":    {"mat_wheat": 2, "mat_butter": 1, "mat_fruit": 2},
        "result_count": 1,
        "desc":         "밀 2개 + 버터 1개 + 과일 2개 → 과일 타르트",
    },
    "snack_chocolate": {
        "name":         "초콜릿 제작",
        "materials":    {"mat_cocoa": 2, "mat_sugar": 1, "mat_milk": 1},
        "result_count": 2,
        "desc":         "코코아 2개 + 설탕 1개 + 우유 1개 → 초콜릿 x2",
    },
    "snack_milk_candy": {
        "name":         "밀크 캔디 제작",
        "materials":    {"mat_milk": 2, "mat_sugar": 1},
        "result_count": 3,
        "desc":         "우유 2개 + 설탕 1개 → 밀크 캔디 x3",
    },
    "snack_magic_macaron": {
        "name":         "마법 마카롱 제작",
        "materials":    {"mat_wheat": 2, "mat_sugar": 2, "mat_butter": 1, "mat_magic_dust": 1},
        "result_count": 1,
        "desc":         "밀 2개 + 설탕 2개 + 버터 1개 + 마법 가루 1개 → 마법 마카롱",
    },
    "snack_popcorn": {
        "name":         "팝콘 제작",
        "materials":    {"mat_wheat": 1, "mat_salt": 1},
        "result_count": 3,
        "desc":         "밀 1개 + 소금 1개 → 팝콘 x3",
    },
    "snack_pudding": {
        "name":         "푸딩 제작",
        "materials":    {"mat_milk": 2, "mat_sugar": 1, "mat_honey": 1},
        "result_count": 1,
        "desc":         "우유 2개 + 설탕 1개 + 꿀 1개 → 푸딩",
    },
}

# ─── 의장 제작 레시피 ────────────────────────────────────────────────────────
COSTUME_RECIPES = {
    # 장난감
    "ct_toy_stick": {
        "name":         "나무 막대 장난감 제작",
        "materials":    {"mat_wood_scrap": 2},
        "result_count": 1,
        "desc":         "나무 조각 2개 → 나무 막대 장난감",
    },
    "ct_toy_ball": {
        "name":         "털실 공 제작",
        "materials":    {"mat_soft_cotton": 3},
        "result_count": 1,
        "desc":         "부드러운 솜 3개 → 털실 공",
    },
    "ct_toy_feather": {
        "name":         "깃털 장난감 제작",
        "materials":    {"mat_wood_scrap": 1, "mat_feather": 2},
        "result_count": 1,
        "desc":         "나무 조각 1개 + 깃털 2개 → 깃털 장난감",
    },
    "ct_toy_magic_wand": {
        "name":         "반짝이 마법봉 제작",
        "materials":    {"mat_wood_scrap": 1, "mat_shiny_button": 2, "mat_magic_thread": 1, "mat_magic_dust": 1},
        "result_count": 1,
        "desc":         "나무 조각 1개 + 반짝이 단추 2개 + 마법실 1개 + 마법 가루 1개 → 반짝이 마법봉",
    },
    # 모자
    "ct_hat_ribbon": {
        "name":         "리본 머리띠 제작",
        "materials":    {"mat_silk_thread": 2, "mat_ribbon_scrap": 1},
        "result_count": 1,
        "desc":         "비단실 2개 + 리본 조각 1개 → 리본 머리띠",
    },
    "ct_hat_flower": {
        "name":         "꽃 화관 제작",
        "materials":    {"mat_silk_thread": 1, "mat_flower_petal": 3},
        "result_count": 1,
        "desc":         "비단실 1개 + 꽃잎 3개 → 꽃 화관",
    },
    "ct_hat_crown": {
        "name":         "작은 왕관 제작",
        "materials":    {"mat_shiny_button": 4, "mat_silk_thread": 2, "mat_ribbon_scrap": 2},
        "result_count": 1,
        "desc":         "반짝이 단추 4개 + 비단실 2개 + 리본 조각 2개 → 작은 왕관",
    },
    "ct_hat_witch": {
        "name":         "마녀 모자 제작",
        "materials":    {"mat_leather_piece": 2, "mat_magic_thread": 2, "mat_silk_thread": 3, "mat_magic_dust": 1},
        "result_count": 1,
        "desc":         "가죽 조각 2개 + 마법실 2개 + 비단실 3개 + 마법 가루 1개 → 마녀 모자",
    },
    # 의상
    "ct_outfit_apron": {
        "name":         "앞치마 제작",
        "materials":    {"mat_soft_cotton": 3, "mat_ribbon_scrap": 1},
        "result_count": 1,
        "desc":         "부드러운 솜 3개 + 리본 조각 1개 → 앞치마",
    },
    "ct_outfit_maid": {
        "name":         "메이드 복장 제작",
        "materials":    {"mat_silk_thread": 4, "mat_soft_cotton": 3, "mat_ribbon_scrap": 2},
        "result_count": 1,
        "desc":         "비단실 4개 + 부드러운 솜 3개 + 리본 조각 2개 → 메이드 복장",
    },
    "ct_outfit_noble": {
        "name":         "귀족 드레스 제작",
        "materials":    {"mat_silk_thread": 5, "mat_shiny_button": 3, "mat_magic_thread": 2},
        "result_count": 1,
        "desc":         "비단실 5개 + 반짝이 단추 3개 + 마법실 2개 → 귀족 드레스",
    },
    "ct_outfit_knight": {
        "name":         "기사단 예복 제작",
        "materials":    {"mat_silk_thread": 6, "mat_leather_piece": 3, "mat_magic_thread": 4, "mat_shiny_button": 4},
        "result_count": 1,
        "desc":         "비단실 6개 + 가죽 조각 3개 + 마법실 4개 + 반짝이 단추 4개 → 기사단 예복",
    },
    # 신발
    "ct_shoes_slippers": {
        "name":         "폭신 슬리퍼 제작",
        "materials":    {"mat_soft_cotton": 2, "mat_ribbon_scrap": 1},
        "result_count": 1,
        "desc":         "부드러운 솜 2개 + 리본 조각 1개 → 폭신 슬리퍼",
    },
    "ct_shoes_boots": {
        "name":         "리본 부츠 제작",
        "materials":    {"mat_leather_piece": 2, "mat_ribbon_scrap": 2},
        "result_count": 1,
        "desc":         "가죽 조각 2개 + 리본 조각 2개 → 리본 부츠",
    },
    "ct_shoes_heels": {
        "name":         "구두 제작",
        "materials":    {"mat_leather_piece": 3, "mat_shiny_button": 2, "mat_silk_thread": 1},
        "result_count": 1,
        "desc":         "가죽 조각 3개 + 반짝이 단추 2개 + 비단실 1개 → 구두",
    },
    "ct_shoes_magic": {
        "name":         "마법 구두 제작",
        "materials":    {"mat_leather_piece": 3, "mat_magic_thread": 3, "mat_shiny_button": 3, "mat_magic_dust": 1},
        "result_count": 1,
        "desc":         "가죽 조각 3개 + 마법실 3개 + 반짝이 단추 3개 + 마법 가루 1개 → 마법 구두",
    },
    # 악세사리
    "ct_acc_bracelet": {
        "name":         "비즈 팔찌 제작",
        "materials":    {"mat_shiny_button": 3, "mat_silk_thread": 1},
        "result_count": 1,
        "desc":         "반짝이 단추 3개 + 비단실 1개 → 비즈 팔찌",
    },
    "ct_acc_necklace": {
        "name":         "꽃잎 목걸이 제작",
        "materials":    {"mat_flower_petal": 3, "mat_silk_thread": 2},
        "result_count": 1,
        "desc":         "꽃잎 3개 + 비단실 2개 → 꽃잎 목걸이",
    },
    "ct_acc_brooch": {
        "name":         "별 브로치 제작",
        "materials":    {"mat_shiny_button": 4, "mat_magic_thread": 1, "mat_silk_thread": 2},
        "result_count": 1,
        "desc":         "반짝이 단추 4개 + 마법실 1개 + 비단실 2개 → 별 브로치",
    },
    "ct_acc_crown_jewel": {
        "name":         "왕관 보석 제작",
        "materials":    {"mat_shiny_button": 5, "mat_magic_thread": 3, "mat_silk_thread": 3, "mat_leather_piece": 2},
        "result_count": 1,
        "desc":         "반짝이 단추 5개 + 마법실 3개 + 비단실 3개 + 가죽 조각 2개 → 왕관 보석",
    },
}

# 등급 표시 텍스트
GRADE_LABELS = {
    "일반": "Normal",
    "고급": "Rare",
    "희귀": "Epic",
    "전설": "Legendary",
}

GRADE_EMOJI = {
    "일반": "⚬",
    "고급": "◆",
    "희귀": "❖",
    "전설": "✦",
}
