"""costume_data.py — 의장 아이템 DB, 간식 아이템 DB, 제작 레시피"""

# ─── 의장 아이템 ────────────────────────────────────────────────────────────
# type: "costume", slot: toy|hat|outfit|shoes|accessory
COSTUME_ITEMS = {
    # ── 장난감 (toy) ──────────────────────────────────────────────────────
    "ct_toy_stick": {
        "name":        "나무 막대 장난감",
        "type":        "costume",
        "slot":        "toy",
        "grade":       "일반",
        "attack": 1,
        "description": "단순하지만 마음을 끄는 나무 막대 장난감.",
        "emoji":       "🪄",
        "price":       0,
    },
    "ct_toy_ball": {
        "name":        "털실 공",
        "type":        "costume",
        "slot":        "toy",
        "grade":       "일반",
        "defense": 1,
        "description": "폭신폭신한 털실로 만든 공.",
        "emoji":       "🧶",
        "price":       0,
    },
    "ct_toy_feather": {
        "name":        "깃털 장난감",
        "type":        "costume",
        "slot":        "toy",
        "grade":       "고급",
        "attack": 3,
        "defense": 1,
        "description": "알록달록한 깃털이 달린 장난감.",
        "emoji":       "🪶",
        "price":       0,
    },
    "ct_toy_magic_wand": {
        "name":        "반짝이 마법봉",
        "type":        "costume",
        "slot":        "toy",
        "grade":       "희귀",
        "attack": 6,
        "description": "반짝이는 별이 달린 마법봉. 기분이 좋아지는 기운이 흐른다.",
        "emoji":       "✨",
        "price":       0,
    },
    # ── 모자 (hat) ────────────────────────────────────────────────────────
    "ct_hat_ribbon": {
        "name":        "리본 머리띠",
        "type":        "costume",
        "slot":        "hat",
        "grade":       "일반",
        "defense": 2,
        "description": "귀여운 리본이 달린 머리띠.",
        "emoji":       "🎀",
        "price":       0,
    },
    "ct_hat_flower": {
        "name":        "꽃 화관",
        "type":        "costume",
        "slot":        "hat",
        "grade":       "일반",
        "defense": 2,
        "description": "들꽃으로 엮어 만든 작은 화관.",
        "emoji":       "🌸",
        "price":       0,
    },
    "ct_hat_crown": {
        "name":        "작은 왕관",
        "type":        "costume",
        "slot":        "hat",
        "grade":       "고급",
        "defense": 5,
        "description": "반짝이는 소재로 만든 미니 왕관.",
        "emoji":       "👑",
        "price":       0,
    },
    "ct_hat_witch": {
        "name":        "마녀 모자",
        "type":        "costume",
        "slot":        "hat",
        "grade":       "희귀",
        "defense": 8,
        "description": "뾰족한 마녀 모자. 신비로운 기운이 감돈다.",
        "emoji":       "🎩",
        "price":       0,
    },
    # ── 의상 (outfit) ─────────────────────────────────────────────────────
    "ct_outfit_apron": {
        "name":        "앞치마",
        "type":        "costume",
        "slot":        "outfit",
        "grade":       "일반",
        "defense": 3,
        "description": "깔끔한 체크 무늬 앞치마.",
        "emoji":       "👘",
        "price":       0,
    },
    "ct_outfit_maid": {
        "name":        "메이드 복장",
        "type":        "costume",
        "slot":        "outfit",
        "grade":       "고급",
        "defense": 7,
        "description": "단정한 메이드 유니폼.",
        "emoji":       "👗",
        "price":       0,
    },
    "ct_outfit_noble": {
        "name":        "귀족 드레스",
        "type":        "costume",
        "slot":        "outfit",
        "grade":       "희귀",
        "defense": 13,
        "description": "화려한 자수가 놓인 귀족 스타일 드레스.",
        "emoji":       "🥻",
        "price":       0,
    },
    "ct_outfit_knight": {
        "name":        "기사단 예복",
        "type":        "costume",
        "slot":        "outfit",
        "grade":       "전설",
        "defense": 22,
        "attack": 5,
        "description": "발더스게이트 기사단의 화려한 예복.",
        "emoji":       "⚔️",
        "price":       0,
    },
    # ── 신발 (shoes) ──────────────────────────────────────────────────────
    "ct_shoes_slippers": {
        "name":        "폭신 슬리퍼",
        "type":        "costume",
        "slot":        "shoes",
        "grade":       "일반",
        "defense": 1,
        "description": "발이 편안한 폭신한 슬리퍼.",
        "emoji":       "🩴",
        "price":       0,
    },
    "ct_shoes_boots": {
        "name":        "리본 부츠",
        "type":        "costume",
        "slot":        "shoes",
        "grade":       "고급",
        "defense": 4,
        "description": "발목에 리본이 달린 귀여운 부츠.",
        "emoji":       "👢",
        "price":       0,
    },
    "ct_shoes_heels": {
        "name":        "구두",
        "type":        "costume",
        "slot":        "shoes",
        "grade":       "희귀",
        "defense": 7,
        "description": "우아한 느낌의 귀족 구두.",
        "emoji":       "👠",
        "price":       0,
    },
    "ct_shoes_magic": {
        "name":        "마법 구두",
        "type":        "costume",
        "slot":        "shoes",
        "grade":       "전설",
        "defense": 12,
        "attack": 3,
        "description": "마법이 깃들어 어디서든 발이 편안한 구두.",
        "emoji":       "✨",
        "price":       0,
    },
    # ── 악세사리 (accessory) ──────────────────────────────────────────────
    "ct_acc_bracelet": {
        "name":        "비즈 팔찌",
        "type":        "costume",
        "slot":        "accessory",
        "grade":       "일반",
        "defense": 1,
        "description": "알록달록한 비즈로 만든 팔찌.",
        "emoji":       "📿",
        "price":       0,
    },
    "ct_acc_necklace": {
        "name":        "꽃잎 목걸이",
        "type":        "costume",
        "slot":        "accessory",
        "grade":       "고급",
        "defense": 3,
        "description": "작은 꽃잎 펜던트가 달린 목걸이.",
        "emoji":       "💐",
        "price":       0,
    },
    "ct_acc_brooch": {
        "name":        "별 브로치",
        "type":        "costume",
        "slot":        "accessory",
        "grade":       "희귀",
        "defense": 5,
        "attack": 2,
        "description": "반짝이는 별 모양 브로치.",
        "emoji":       "⭐",
        "price":       0,
    },
    "ct_acc_crown_jewel": {
        "name":        "왕관 보석",
        "type":        "costume",
        "slot":        "accessory",
        "grade":       "전설",
        "defense": 10,
        "attack": 5,
        "description": "왕가의 보석. 착용자에게 위엄을 부여한다.",
        "emoji":       "💎",
        "price":       0,
    },
}

# ─── 간식 아이템 ────────────────────────────────────────────────────────────
SNACK_ITEMS = {
    "snack_cookie": {
        "name":        "수제 쿠키",
        "type":        "snack",
        "grade":       "일반",
        "effect":      {"condition": 10, "fatigue": -5},
        "description": "달콤한 수제 쿠키. 기분을 조금 좋게 해줌미댜.",
        "emoji":       "🍪",
        "price":       0,
    },
    "snack_cake": {
        "name":        "작은 케이크",
        "type":        "snack",
        "grade":       "고급",
        "effect":      {"condition": 20, "stability": 5, "fatigue": -8},
        "description": "예쁘게 장식된 작은 케이크.",
        "emoji":       "🎂",
        "price":       0,
    },
    "snack_honey_bread": {
        "name":        "꿀빵",
        "type":        "snack",
        "grade":       "일반",
        "effect":      {"condition": 12, "fatigue": -6},
        "description": "달콤한 꿀을 듬뿍 바른 빵.",
        "emoji":       "🍞",
        "price":       0,
    },
    "snack_fruit_tart": {
        "name":        "과일 타르트",
        "type":        "snack",
        "grade":       "고급",
        "effect":      {"condition": 18, "stability": 8, "fatigue": -5},
        "description": "신선한 과일로 만든 타르트.",
        "emoji":       "🫐",
        "price":       0,
    },
    "snack_chocolate": {
        "name":        "초콜릿",
        "type":        "snack",
        "grade":       "일반",
        "effect":      {"condition": 8, "stability": 5},
        "description": "달콤쌉싸름한 초콜릿.",
        "emoji":       "🍫",
        "price":       0,
    },
    "snack_milk_candy": {
        "name":        "밀크 캔디",
        "type":        "snack",
        "grade":       "일반",
        "effect":      {"condition": 7, "fatigue": -3},
        "description": "우유로 만든 부드러운 사탕.",
        "emoji":       "🍬",
        "price":       0,
    },
    "snack_magic_macaron": {
        "name":        "마법 마카롱",
        "type":        "snack",
        "grade":       "희귀",
        "effect":      {"condition": 30, "stability": 15, "fatigue": -15},
        "description": "마법 재료로 만든 특제 마카롱. 몸과 마음이 회복된다.",
        "emoji":       "🧁",
        "price":       0,
    },
    "snack_popcorn": {
        "name":        "팝콘",
        "type":        "snack",
        "grade":       "일반",
        "effect":      {"condition": 5, "fatigue": -2},
        "description": "바삭바삭한 팝콘.",
        "emoji":       "🍿",
        "price":       0,
    },
    "snack_pudding": {
        "name":        "푸딩",
        "type":        "snack",
        "grade":       "고급",
        "effect":      {"condition": 15, "stability": 10, "fatigue": -7},
        "description": "흔들흔들 맛있는 푸딩.",
        "emoji":       "🍮",
        "price":       0,
    },
    "snack_legendary_feast": {
        "name":        "전설의 만찬",
        "type":        "snack",
        "grade":       "전설",
        "effect":      {"condition": 50, "stability": 25, "fatigue": -30},
        "description": "발더스게이트의 최고 요리사가 만든 전설적인 요리.",
        "emoji":       "🍽️",
        "price":       0,
    },
}

# ─── 간식 제작 레시피 ────────────────────────────────────────────────────────
SNACK_RECIPES = {
    "snack_cookie": {
        "name":         "수제 쿠키 제작",
        "materials":    {"mat_wheat": 2, "mat_sugar": 1},
        "result_count": 2,
        "desc":         "밀 2개 + 설탕 1개 → 수제 쿠키 x2",
    },
    "snack_cake": {
        "name":         "작은 케이크 제작",
        "materials":    {"mat_wheat": 3, "mat_sugar": 2, "mat_butter": 1},
        "result_count": 1,
        "desc":         "밀 3개 + 설탕 2개 + 버터 1개 → 작은 케이크",
    },
    "snack_honey_bread": {
        "name":         "꿀빵 제작",
        "materials":    {"mat_wheat": 2, "mat_honey": 1},
        "result_count": 2,
        "desc":         "밀 2개 + 꿀 1개 → 꿀빵 x2",
    },
    "snack_fruit_tart": {
        "name":         "과일 타르트 제작",
        "materials":    {"mat_wheat": 2, "mat_butter": 1, "mat_fruit": 2},
        "result_count": 1,
        "desc":         "밀 2개 + 버터 1개 + 과일 2개 → 과일 타르트",
    },
    "snack_chocolate": {
        "name":         "초콜릿 제작",
        "materials":    {"mat_cocoa": 2, "mat_sugar": 1, "mat_milk": 1},
        "result_count": 2,
        "desc":         "코코아 2개 + 설탕 1개 + 우유 1개 → 초콜릿 x2",
    },
    "snack_milk_candy": {
        "name":         "밀크 캔디 제작",
        "materials":    {"mat_milk": 2, "mat_sugar": 1},
        "result_count": 3,
        "desc":         "우유 2개 + 설탕 1개 → 밀크 캔디 x3",
    },
    "snack_magic_macaron": {
        "name":         "마법 마카롱 제작",
        "materials":    {"mat_wheat": 2, "mat_sugar": 2, "mat_butter": 1, "mat_magic_dust": 1},
        "result_count": 1,
        "desc":         "밀 2개 + 설탕 2개 + 버터 1개 + 마법 가루 1개 → 마법 마카롱",
    },
    "snack_popcorn": {
        "name":         "팝콘 제작",
        "materials":    {"mat_wheat": 1, "mat_salt": 1},
        "result_count": 3,
        "desc":         "밀 1개 + 소금 1개 → 팝콘 x3",
    },
    "snack_pudding": {
        "name":         "푸딩 제작",
        "materials":    {"mat_milk": 2, "mat_sugar": 1, "mat_honey": 1},
        "result_count": 1,
        "desc":         "우유 2개 + 설탕 1개 + 꿀 1개 → 푸딩",
    },
}

# ─── 의장 제작 레시피 ────────────────────────────────────────────────────────
COSTUME_RECIPES = {
    # 장난감
    "ct_toy_stick": {
        "name":         "나무 막대 장난감 제작",
        "materials":    {"mat_wood_scrap": 2},
        "result_count": 1,
        "desc":         "나무 조각 2개 → 나무 막대 장난감",
    },
    "ct_toy_ball": {
        "name":         "털실 공 제작",
        "materials":    {"mat_soft_cotton": 3},
        "result_count": 1,
        "desc":         "부드러운 솜 3개 → 털실 공",
    },
    "ct_toy_feather": {
        "name":         "깃털 장난감 제작",
        "materials":    {"mat_wood_scrap": 1, "mat_feather": 2},
        "result_count": 1,
        "desc":         "나무 조각 1개 + 깃털 2개 → 깃털 장난감",
    },
    "ct_toy_magic_wand": {
        "name":         "반짝이 마법봉 제작",
        "materials":    {"mat_wood_scrap": 1, "mat_shiny_button": 3, "mat_magic_thread": 1},
        "result_count": 1,
        "desc":         "나무 조각 1개 + 반짝이 단추 3개 + 마법실 1개 → 반짝이 마법봉",
    },
    # 모자
    "ct_hat_ribbon": {
        "name":         "리본 머리띠 제작",
        "materials":    {"mat_silk_thread": 2, "mat_ribbon_scrap": 1},
        "result_count": 1,
        "desc":         "비단실 2개 + 리본 조각 1개 → 리본 머리띠",
    },
    "ct_hat_flower": {
        "name":         "꽃 화관 제작",
        "materials":    {"mat_silk_thread": 1, "mat_flower_petal": 3},
        "result_count": 1,
        "desc":         "비단실 1개 + 꽃잎 3개 → 꽃 화관",
    },
    "ct_hat_crown": {
        "name":         "작은 왕관 제작",
        "materials":    {"mat_shiny_button": 4, "mat_silk_thread": 2, "mat_ribbon_scrap": 2},
        "result_count": 1,
        "desc":         "반짝이 단추 4개 + 비단실 2개 + 리본 조각 2개 → 작은 왕관",
    },
    "ct_hat_witch": {
        "name":         "마녀 모자 제작",
        "materials":    {"mat_leather_piece": 2, "mat_magic_thread": 2, "mat_silk_thread": 3},
        "result_count": 1,
        "desc":         "가죽 조각 2개 + 마법실 2개 + 비단실 3개 → 마녀 모자",
    },
    # 의상
    "ct_outfit_apron": {
        "name":         "앞치마 제작",
        "materials":    {"mat_soft_cotton": 3, "mat_ribbon_scrap": 1},
        "result_count": 1,
        "desc":         "부드러운 솜 3개 + 리본 조각 1개 → 앞치마",
    },
    "ct_outfit_maid": {
        "name":         "메이드 복장 제작",
        "materials":    {"mat_silk_thread": 4, "mat_soft_cotton": 3, "mat_ribbon_scrap": 2},
        "result_count": 1,
        "desc":         "비단실 4개 + 부드러운 솜 3개 + 리본 조각 2개 → 메이드 복장",
    },
    "ct_outfit_noble": {
        "name":         "귀족 드레스 제작",
        "materials":    {"mat_silk_thread": 5, "mat_shiny_button": 3, "mat_magic_thread": 2},
        "result_count": 1,
        "desc":         "비단실 5개 + 반짝이 단추 3개 + 마법실 2개 → 귀족 드레스",
    },
    "ct_outfit_knight": {
        "name":         "기사단 예복 제작",
        "materials":    {"mat_silk_thread": 6, "mat_leather_piece": 3, "mat_magic_thread": 4, "mat_shiny_button": 4},
        "result_count": 1,
        "desc":         "비단실 6개 + 가죽 조각 3개 + 마법실 4개 + 반짝이 단추 4개 → 기사단 예복",
    },
    # 신발
    "ct_shoes_slippers": {
        "name":         "폭신 슬리퍼 제작",
        "materials":    {"mat_soft_cotton": 2, "mat_ribbon_scrap": 1},
        "result_count": 1,
        "desc":         "부드러운 솜 2개 + 리본 조각 1개 → 폭신 슬리퍼",
    },
    "ct_shoes_boots": {
        "name":         "리본 부츠 제작",
        "materials":    {"mat_leather_piece": 2, "mat_ribbon_scrap": 2},
        "result_count": 1,
        "desc":         "가죽 조각 2개 + 리본 조각 2개 → 리본 부츠",
    },
    "ct_shoes_heels": {
        "name":         "구두 제작",
        "materials":    {"mat_leather_piece": 3, "mat_shiny_button": 2, "mat_silk_thread": 1},
        "result_count": 1,
        "desc":         "가죽 조각 3개 + 반짝이 단추 2개 + 비단실 1개 → 구두",
    },
    "ct_shoes_magic": {
        "name":         "마법 구두 제작",
        "materials":    {"mat_leather_piece": 3, "mat_magic_thread": 3, "mat_shiny_button": 3},
        "result_count": 1,
        "desc":         "가죽 조각 3개 + 마법실 3개 + 반짝이 단추 3개 → 마법 구두",
    },
    # 악세사리
    "ct_acc_bracelet": {
        "name":         "비즈 팔찌 제작",
        "materials":    {"mat_shiny_button": 3, "mat_silk_thread": 1},
        "result_count": 1,
        "desc":         "반짝이 단추 3개 + 비단실 1개 → 비즈 팔찌",
    },
    "ct_acc_necklace": {
        "name":         "꽃잎 목걸이 제작",
        "materials":    {"mat_flower_petal": 3, "mat_silk_thread": 2},
        "result_count": 1,
        "desc":         "꽃잎 3개 + 비단실 2개 → 꽃잎 목걸이",
    },
    "ct_acc_brooch": {
        "name":         "별 브로치 제작",
        "materials":    {"mat_shiny_button": 4, "mat_magic_thread": 1, "mat_silk_thread": 2},
        "result_count": 1,
        "desc":         "반짝이 단추 4개 + 마법실 1개 + 비단실 2개 → 별 브로치",
    },
    "ct_acc_crown_jewel": {
        "name":         "왕관 보석 제작",
        "materials":    {"mat_shiny_button": 5, "mat_magic_thread": 3, "mat_silk_thread": 3, "mat_leather_piece": 2},
        "result_count": 1,
        "desc":         "반짝이 단추 5개 + 마법실 3개 + 비단실 3개 + 가죽 조각 2개 → 왕관 보석",
    },
}

# 등급 표시 텍스트
GRADE_LABELS = {
    "일반": "Normal",
    "고급": "Rare",
    "희귀": "Epic",
    "전설": "Legendary",
}

GRADE_EMOJI = {
    "일반": "⚬",
    "고급": "◆",
    "희귀": "❖",
    "전설": "✦",
}
