WEAPONS = {
    "wp_sword_01": {
        "name": "낡은 검",
        "type": "weapon",
        "subtype": "sword",
        "grade": "Normal",
        "attack": 12,
        "price": 500,
        "desc": "오래된 한손검. 기본 성능을 가진다.",
        "slot": "main",
    },
    "wp_sword_02": {
        "name": "철제 롱소드",
        "type": "weapon",
        "subtype": "sword",
        "grade": "Rare",
        "attack": 28,
        "price": 2500,
        "desc": "견고한 철로 제작된 롱소드.",
        "slot": "main",
    },
    "wp_bow_01": {
        "name": "나무 활",
        "type": "weapon",
        "subtype": "bow",
        "grade": "Normal",
        "attack": 10,
        "price": 400,
        "desc": "가벼운 나무 활.",
        "slot": "main",
    },
    "wp_bow_02": {
        "name": "합성 활",
        "type": "weapon",
        "subtype": "bow",
        "grade": "Rare",
        "attack": 24,
        "price": 2200,
        "desc": "여러 소재로 만든 강화된 활.",
        "slot": "main",
    },
    "wp_staff_01": {
        "name": "나무 지팡이",
        "type": "weapon",
        "subtype": "staff",
        "grade": "Normal",
        "attack": 8,
        "magic_attack": 15,
        "price": 600,
        "desc": "마력을 담은 나무 지팡이.",
        "slot": "main",
    },
    "wp_wand_01": {
        "name": "마법 완드",
        "type": "weapon",
        "subtype": "wand",
        "grade": "Rare",
        "attack": 6,
        "magic_attack": 30,
        "price": 3000,
        "desc": "마법 집중력이 높은 완드.",
        "slot": "main",
    },
    "wp_mace_01": {
        "name": "철제 메이스",
        "type": "weapon",
        "subtype": "mace",
        "grade": "Normal",
        "attack": 15,
        "price": 700,
        "desc": "둔기형 한손 무기.",
        "slot": "main",
    },
    "wp_hammer_01": {
        "name": "전투 해머",
        "type": "weapon",
        "subtype": "hammer",
        "grade": "Rare",
        "attack": 35,
        "price": 3500,
        "desc": "강력한 충격을 주는 양손 해머.",
        "slot": "main",
    },
}

ARMORS = {
    "ar_shield_01": {
        "name": "나무 방패",
        "type": "armor",
        "subtype": "shield",
        "grade": "Normal",
        "defense": 5,
        "price": 300,
        "desc": "가벼운 나무 방패.",
        "slot": "sub",
    },
    "ar_shield_02": {
        "name": "철제 방패",
        "type": "armor",
        "subtype": "shield",
        "grade": "Rare",
        "defense": 18,
        "price": 2000,
        "desc": "단단한 철제 방패.",
        "slot": "sub",
    },
    "ar_armor_01": {
        "name": "가죽 갑옷",
        "type": "armor",
        "subtype": "body",
        "grade": "Normal",
        "defense": 10,
        "price": 800,
        "desc": "기동성이 좋은 가죽 갑옷.",
        "slot": "body",
    },
    "ar_armor_02": {
        "name": "사슬 갑옷",
        "type": "armor",
        "subtype": "body",
        "grade": "Rare",
        "defense": 22,
        "price": 2800,
        "desc": "사슬로 엮어 만든 방어구.",
        "slot": "body",
    },
    "ar_armor_03": {
        "name": "철판 갑옷",
        "type": "armor",
        "subtype": "body",
        "grade": "Epic",
        "defense": 40,
        "price": 7000,
        "desc": "두꺼운 철판으로 만든 중갑.",
        "slot": "body",
    },
}

CONSUMABLES = {
    "con_bread": {
        "name": "빵",
        "type": "consumable",
        "grade": "Normal",
        "price": 50,
        "desc": "허기를 채우는 빵. 체력을 소량 회복.",
        "hp": 20,
        "mp": 0,
        "en": 10,
    },
    "con_milk": {
        "name": "우유",
        "type": "consumable",
        "grade": "Normal",
        "price": 40,
        "desc": "신선한 우유. MP를 소량 회복.",
        "hp": 5,
        "mp": 15,
        "en": 5,
    },
    "con_potion_h": {
        "name": "회복 포션",
        "type": "consumable",
        "grade": "Normal",
        "price": 200,
        "desc": "HP를 중간 정도 회복시키는 포션.",
        "hp": 100,
        "mp": 0,
        "en": 0,
    },
    "con_herb_01": {
        "name": "약초",
        "type": "consumable",
        "grade": "Normal",
        "price": 30,
        "desc": "야생에서 채집한 약초. HP 소량 회복.",
        "hp": 15,
        "mp": 5,
        "en": 0,
    },
}

GATHERING_ITEMS = {
    "gt_herb_01": {
        "name": "들풀",
        "type": "gathering",
        "grade": "Normal",
        "price": 15,
        "desc": "들판에서 채집한 풀.",
    },
    "gt_wood_01": {
        "name": "나무 조각",
        "type": "gathering",
        "grade": "Normal",
        "price": 20,
        "desc": "숲에서 채집한 나무 조각.",
    },
    "gt_flower_01": {
        "name": "들꽃",
        "type": "gathering",
        "grade": "Normal",
        "price": 25,
        "desc": "들판에 핀 예쁜 꽃.",
    },
}

LOOT_ITEMS = {
    "lt_leather_01": {
        "name": "가죽",
        "type": "loot",
        "grade": "Normal",
        "price": 40,
        "desc": "몬스터에게서 얻은 가죽.",
    },
    "lt_tooth_01": {
        "name": "이빨",
        "type": "loot",
        "grade": "Normal",
        "price": 35,
        "desc": "몬스터의 날카로운 이빨.",
    },
    "lt_core_01": {
        "name": "마력 코어",
        "type": "loot",
        "grade": "Rare",
        "price": 250,
        "desc": "마법 몬스터의 핵심 부위.",
    },
}

FISH_ITEMS = {
    "fs_carp_01": {
        "name": "잉어",
        "type": "fish",
        "grade": "Normal",
        "price": 60,
        "desc": "강에서 잡은 잉어.",
    },
    "fs_salmon_01": {
        "name": "연어",
        "type": "fish",
        "grade": "Rare",
        "price": 180,
        "desc": "싱싱한 연어.",
    },
    "fs_eel_01": {
        "name": "장어",
        "type": "fish",
        "grade": "Rare",
        "price": 220,
        "desc": "탱탱한 장어.",
    },
}

COOKED_DISHES = {
    "ck_soup_01": {
        "name": "야채 수프",
        "type": "cooked",
        "grade": "Normal",
        "price": 100,
        "desc": "따뜻한 야채 수프. HP·EN 회복.",
        "hp": 40,
        "mp": 10,
        "en": 20,
    },
    "ck_steak_01": {
        "name": "고기 스테이크",
        "type": "cooked",
        "grade": "Rare",
        "price": 300,
        "desc": "두툼한 스테이크. HP 대량 회복.",
        "hp": 120,
        "mp": 0,
        "en": 40,
    },
    "ck_special_01": {
        "name": "특제 도시락",
        "type": "cooked",
        "grade": "Epic",
        "price": 800,
        "desc": "정성껏 만든 특제 도시락. 모든 수치 회복.",
        "hp": 200,
        "mp": 80,
        "en": 80,
    },
}

# 몬스터 드랍 아이템
DROP_ITEMS = {
    "spider_web": {
        "name": "거미줄",
        "type": "loot",
        "grade": "Normal",
        "price": 20,
        "desc": "거미에게서 얻은 거미줄.",
    },
    "iron_ore": {
        "name": "철광석",
        "type": "ore",
        "grade": "Normal",
        "price": 80,
        "desc": "철을 함유한 광석.",
    },
    "copper_ore": {
        "name": "구리 광석",
        "type": "ore",
        "grade": "Normal",
        "price": 60,
        "desc": "구리를 함유한 광석.",
    },
    "hard_horn": {
        "name": "단단한 뿔",
        "type": "loot",
        "grade": "Normal",
        "price": 90,
        "desc": "몬스터의 단단한 뿔.",
    },
    "bear_paw": {
        "name": "곰 발바닥",
        "type": "loot",
        "grade": "Rare",
        "price": 200,
        "desc": "곰에게서 얻은 발바닥.",
    },
    "honey": {
        "name": "꿀",
        "type": "gathering",
        "grade": "Normal",
        "price": 70,
        "desc": "달콤한 꿀.",
        "hp": 10,
        "mp": 10,
        "en": 5,
    },
    "herb": {
        "name": "허브",
        "type": "gathering",
        "grade": "Normal",
        "price": 25,
        "desc": "신선한 허브.",
        "hp": 8,
        "mp": 5,
        "en": 0,
    },
    "water": {
        "name": "물",
        "type": "ingredient",
        "grade": "Normal",
        "price": 5,
        "desc": "깨끗한 물.",
    },
    "feather": {
        "name": "깃털",
        "type": "loot",
        "grade": "Normal",
        "price": 30,
        "desc": "부드러운 깃털.",
    },
    "wing": {
        "name": "날개",
        "type": "loot",
        "grade": "Rare",
        "price": 150,
        "desc": "몬스터의 날개.",
    },
    "coal": {
        "name": "석탄",
        "type": "ore",
        "grade": "Normal",
        "price": 40,
        "desc": "검은 석탄 덩어리.",
    },
    "mp_crystal": {
        "name": "마력 결정",
        "type": "loot",
        "grade": "Rare",
        "price": 300,
        "desc": "마력이 응축된 결정.",
        "mp": 50,
    },
    "silver_ore": {
        "name": "은 광석",
        "type": "ore",
        "grade": "Rare",
        "price": 200,
        "desc": "은을 함유한 광석.",
    },
    "gold_ore": {
        "name": "금 광석",
        "type": "ore",
        "grade": "Rare",
        "price": 400,
        "desc": "금을 함유한 광석.",
    },
    "mithril_ore": {
        "name": "미스릴 광석",
        "type": "ore",
        "grade": "Epic",
        "price": 1500,
        "desc": "희귀한 미스릴 광석.",
    },
    "re_stone": {
        "name": "부활석",
        "type": "loot",
        "grade": "Epic",
        "price": 2000,
        "desc": "부활의 기운이 담긴 돌.",
    },
    "poison_sac": {
        "name": "독주머니",
        "type": "loot",
        "grade": "Rare",
        "price": 180,
        "desc": "독이 든 주머니.",
    },
    "sulfur": {
        "name": "유황",
        "type": "ore",
        "grade": "Normal",
        "price": 55,
        "desc": "노란 유황 덩어리.",
    },
    "ruby": {
        "name": "루비",
        "type": "gem",
        "grade": "Epic",
        "price": 3000,
        "desc": "붉게 빛나는 루비.",
    },
    "sapphire": {
        "name": "사파이어",
        "type": "gem",
        "grade": "Epic",
        "price": 3000,
        "desc": "파랗게 빛나는 사파이어.",
    },
    "emerald": {
        "name": "에메랄드",
        "type": "gem",
        "grade": "Epic",
        "price": 3000,
        "desc": "초록빛 에메랄드.",
    },
    "diamond": {
        "name": "다이아몬드",
        "type": "gem",
        "grade": "Legendary",
        "price": 10000,
        "desc": "투명하게 빛나는 다이아몬드.",
    },
    "diamond_7": {
        "name": "7성 다이아몬드",
        "type": "gem",
        "grade": "Legendary",
        "price": 50000,
        "desc": "전설 등급의 순수한 다이아몬드.",
    },
    "dragon_bacon": {
        "name": "드래곤 베이컨",
        "type": "loot",
        "grade": "Legendary",
        "price": 20000,
        "desc": "드래곤에게서 얻은 희귀한 베이컨.",
    },
    "ancient_scale": {
        "name": "고대 비늘",
        "type": "loot",
        "grade": "Legendary",
        "price": 15000,
        "desc": "고대 드래곤의 비늘.",
    },
    "rotten_meat": {
        "name": "썩은 고기",
        "type": "loot",
        "grade": "Normal",
        "price": 5,
        "desc": "썩은 고기 덩어리. 쓸모없어 보인다.",
    },
    "mana_herb": {
        "name": "마나 허브",
        "type": "ingredient",
        "grade": "Rare",
        "price": 120,
        "desc": "마력을 회복시키는 허브.",
        "mp": 30,
    },
    "eye_of_truth": {
        "name": "진실의 눈",
        "type": "loot",
        "grade": "Epic",
        "price": 5000,
        "desc": "모든 것을 꿰뚫어 보는 눈.",
    },
    "pot_potion": {
        "name": "특제 포션",
        "type": "consumable",
        "grade": "Rare",
        "price": 800,
        "desc": "강력한 회복력의 특제 포션.",
        "hp": 300,
        "mp": 100,
        "en": 0,
    },
    "bad_score": {
        "name": "실패한 악보",
        "type": "loot",
        "grade": "Normal",
        "price": 10,
        "desc": "엉망으로 쓴 악보.",
    },
    "fire_wand": {
        "name": "화염 완드",
        "type": "weapon",
        "subtype": "wand",
        "grade": "Epic",
        "attack": 10,
        "magic_attack": 60,
        "price": 8000,
        "desc": "화염 마법이 깃든 완드.",
        "slot": "main",
    },
    "short_bow": {
        "name": "단궁",
        "type": "weapon",
        "subtype": "bow",
        "grade": "Normal",
        "attack": 8,
        "price": 350,
        "desc": "짧고 가벼운 활.",
        "slot": "main",
    },
    "club": {
        "name": "몽둥이",
        "type": "weapon",
        "subtype": "mace",
        "grade": "Normal",
        "attack": 7,
        "price": 100,
        "desc": "단순한 나무 몽둥이.",
        "slot": "main",
    },
    "plate_mail": {
        "name": "플레이트 메일",
        "type": "armor",
        "subtype": "body",
        "grade": "Epic",
        "defense": 50,
        "price": 9000,
        "desc": "최고급 판금 갑옷.",
        "slot": "body",
    },
    "claymore": {
        "name": "클레이모어",
        "type": "weapon",
        "subtype": "sword",
        "grade": "Epic",
        "attack": 55,
        "price": 12000,
        "desc": "거대한 양손 대검.",
        "slot": "main",
    },
    "dark_matter": {
        "name": "어둠의 결정",
        "type": "loot",
        "grade": "Legendary",
        "price": 25000,
        "desc": "어둠의 기운이 응집된 결정체.",
    },
}

# 요리 재료
INGREDIENTS = {
    "flour": {
        "name": "밀가루",
        "type": "ingredient",
        "grade": "Normal",
        "price": 10,
        "desc": "요리에 쓰이는 밀가루.",
    },
    "sugar": {
        "name": "설탕",
        "type": "ingredient",
        "grade": "Normal",
        "price": 10,
        "desc": "단맛을 내는 설탕.",
    },
    "salt": {
        "name": "소금",
        "type": "ingredient",
        "grade": "Normal",
        "price": 8,
        "desc": "짠맛을 내는 소금.",
    },
    "egg": {
        "name": "달걀",
        "type": "ingredient",
        "grade": "Normal",
        "price": 15,
        "desc": "신선한 달걀.",
    },
    "milk": {
        "name": "우유 원액",
        "type": "ingredient",
        "grade": "Normal",
        "price": 20,
        "desc": "요리에 사용하는 우유.",
    },
    "mushroom": {
        "name": "버섯",
        "type": "ingredient",
        "grade": "Normal",
        "price": 30,
        "desc": "숲에서 채취한 버섯.",
    },
    "yeast": {
        "name": "효모",
        "type": "ingredient",
        "grade": "Normal",
        "price": 20,
        "desc": "발효에 쓰이는 효모.",
    },
    "oil": {
        "name": "식용유",
        "type": "ingredient",
        "grade": "Normal",
        "price": 25,
        "desc": "요리에 사용하는 기름.",
    },
    "coffee_bean": {
        "name": "커피 원두",
        "type": "ingredient",
        "grade": "Rare",
        "price": 80,
        "desc": "향긋한 커피 원두.",
    },
    "potato": {
        "name": "감자",
        "type": "ingredient",
        "grade": "Normal",
        "price": 20,
        "desc": "탐스러운 감자.",
    },
    "soy_bean": {
        "name": "대두",
        "type": "ingredient",
        "grade": "Normal",
        "price": 15,
        "desc": "고소한 대두.",
    },
    "wine": {
        "name": "포도주",
        "type": "ingredient",
        "grade": "Rare",
        "price": 150,
        "desc": "향긋한 포도주.",
    },
    "bread": {
        "name": "빵 반죽",
        "type": "ingredient",
        "grade": "Normal",
        "price": 30,
        "desc": "반죽된 빵 재료.",
    },
}

# 제련 주괴
BAR_ITEMS = {
    "copper_bar": {
        "name": "구리 주괴",
        "type": "bar",
        "grade": "Normal",
        "price": 150,
        "desc": "구리를 제련한 주괴.",
    },
    "iron_bar": {
        "name": "철 주괴",
        "type": "bar",
        "grade": "Normal",
        "price": 200,
        "desc": "철을 제련한 주괴.",
    },
    "silver_bar": {
        "name": "은 주괴",
        "type": "bar",
        "grade": "Rare",
        "price": 500,
        "desc": "은을 제련한 주괴.",
    },
    "gold_bar": {
        "name": "금 주괴",
        "type": "bar",
        "grade": "Rare",
        "price": 1000,
        "desc": "금을 제련한 주괴.",
    },
    "mithril_bar": {
        "name": "미스릴 주괴",
        "type": "bar",
        "grade": "Epic",
        "price": 4000,
        "desc": "미스릴을 제련한 주괴.",
    },
    "slag": {
        "name": "쇳물 찌꺼기",
        "type": "loot",
        "grade": "Normal",
        "price": 5,
        "desc": "제련 과정에서 나온 찌꺼기.",
    },
    "mithril_dust": {
        "name": "미스릴 가루",
        "type": "loot",
        "grade": "Rare",
        "price": 300,
        "desc": "미스릴 정제 시 나오는 가루.",
    },
}

ALL_ITEMS = {
    **WEAPONS,
    **ARMORS,
    **CONSUMABLES,
    **GATHERING_ITEMS,
    **LOOT_ITEMS,
    **FISH_ITEMS,
    **COOKED_DISHES,
    **DROP_ITEMS,
    **INGREDIENTS,
    **BAR_ITEMS,
}
