(()=>{
'use strict';
const BPM=136,BEAT=60000/BPM;
const MODES={easy:{keys:['d','f','j','k'],label:'EASY · 4K',pattern:[0,1,2,3,1,2,0,3,0,2,1,3,0,1,2,3,1,3,0,2,0,1,3,2,1,2,0,3,0,2,3,1]},hard:{keys:['a','s','d','f','h','j','k','l'],label:'EXPERT · 8K',pattern:[0,4,2,6,1,5,3,7,0,3,4,7,1,2,5,6,0,4,1,5,2,6,3,7,0,2,4,6,1,3,5,7,0,7,2,5,1,6,3,4,0,4,2,6,1,5,3,7,0,3,5,7,1,2,4,6,0,4,1,5,2,6,3,7]}};
const els={stage:q('#stage'),lanes:q('#lanes'),judge:q('#judge'),countdown:q('#countdown'),score:q('#score'),combo:q('#combo'),status:q('#status'),accuracy:q('#accuracy'),song:q('#song'),start:q('#start'),speed:q('#speed'),runes:q('#runes'),phase:q('#phase'),memory:q('#memory')};
let mode='easy',chart=[],running=false,startAt=0,raf=0,combo=0,score=0,hits=0,judged=0,totalErr=0,runes=0,phase='theme',memory=[],memoryReady=false;
const travel=1800,windows={perfect:45,great:85,good:130};function q(s){return document.querySelector(s)}function playbackSpeed(){return Number(els.speed.value)||1}
function makeNote(t,lane,type='normal'){return{t,lane,type,hit:false,miss:false,el:null}}
function buildChart(){const speed=playbackSpeed(),step=(mode==='easy'?BEAT:BEAT/2)/speed,base=MODES[mode].pattern.map((lane,i)=>makeNote((900+i*(mode==='easy'?BEAT:BEAT/2))/speed,lane));chart=base;if(mode==='hard'){const end=base.at(-1).t;const recall=[];for(let i=0;i<8;i++)recall.push(makeNote(end+BEAT/speed+(i*step),i%8,'recall'));chart=chart.concat(recall)}}
function buildLanes(){els.lanes.innerHTML='';els.lanes.className='lanes '+(mode==='hard'?'hard':'');MODES[mode].keys.forEach(k=>{const lane=document.createElement('div');lane.className='lane';lane.innerHTML=`<span class="lane-key">${k.toUpperCase()}</span>`;els.lanes.appendChild(lane)})}
function reset(){cancelAnimationFrame(raf);els.song.pause();els.song.currentTime=0;running=false;combo=score=hits=judged=totalErr=runes=0;phase='theme';memory=[];memoryReady=false;buildChart();buildLanes();updateHud();els.judge.textContent='READY';els.judge.className='judge';els.phase.textContent='주제';els.memory.textContent=mode==='hard'?'즉흥 프레이즈를 기다리는 중':'정석 연주';renderRunes()}
function renderRunes(){els.runes.innerHTML='';for(let i=0;i<4;i++){const r=document.createElement('i');r.textContent='◇';r.className=i<runes?'lit':'';els.runes.appendChild(r)}}
function updateHud(){els.score.textContent=String(score).padStart(6,'0');els.combo.textContent=`COMBO ${combo}`;els.accuracy.textContent=judged?`ACC ${(Math.max(0,100-totalErr/judged/1.3)).toFixed(2)}%`:'ACC --%'}function flash(t,c){els.judge.textContent=t;els.judge.className='judge '+c}function now(){return performance.now()-startAt}
function phaseUpdate(t){if(mode!=='hard')return;const last=MODES.hard.pattern.length-1,step=(BEAT/2)/playbackSpeed(),improvStart=chart[Math.floor(last*.55)].t,improvEnd=chart[Math.floor(last*.72)].t;if(t>=improvStart&&t<improvEnd&&phase!=='improv'){phase='improv';els.phase.textContent='자유 즉흥';els.memory.textContent='당신의 8음을 기억합니다';els.stage.classList.add('improv')}else if(t>=improvEnd&&phase==='improv'){phase='recall';memoryReady=true;els.phase.textContent='그림자 회상';els.stage.classList.remove('improv');const tail=chart.slice(-8);if(memory.length){tail.forEach((n,i)=>n.lane=(7-memory[i%memory.length].lane));els.memory.textContent='당신의 프레이즈 · 좌우 반전'}else els.memory.textContent='기억된 음이 없어 기본 변주'}}
function frame(){if(!running)return;const t=now(),h=els.stage.clientHeight,judgeY=h-49;phaseUpdate(t);chart.forEach(n=>{if(n.hit||n.miss)return;const dt=n.t-t;if(dt < -windows.good){n.miss=true;judged++;combo=0;totalErr+=130;flash('MISS','miss');updateHud();if(n.el)n.el.remove();return}if(dt>travel||dt<-windows.good)return;if(!n.el){n.el=document.createElement('div');n.el.className='note '+n.type;els.lanes.children[n.lane].appendChild(n.el)}const y=judgeY-(dt/travel)*(judgeY-20);n.el.style.top=`${y}px`});if(t>chart.at(-1).t+900){finish();return}raf=requestAnimationFrame(frame)}
function press(key){if(!running)return;const lane=MODES[mode].keys.indexOf(key);if(lane<0)return;const laneEl=els.lanes.children[lane];laneEl.classList.add('pressed');setTimeout(()=>laneEl.classList.remove('pressed'),70);const t=now();if(mode==='hard'&&phase==='improv'&&memory.length<8){memory.push({lane,dt:t});els.memory.textContent=`기억한 프레이즈 ${memory.length}/8`;if(memory.length===8)flash('MEMORY SEALED','perfect')}let best=null,err=Infinity;chart.forEach(n=>{if(n.lane!==lane||n.hit||n.miss)return;const e=Math.abs(n.t-t);if(e<err){err=e;best=n}});if(!best||err>windows.good){combo=0;flash(phase==='improv'?'IMPROVISE':'MISS',phase==='improv'?'great':'miss');updateHud();return}best.hit=true;judged++;hits++;totalErr+=err;combo++;let pts,txt,cls;if(err<=windows.perfect){pts=1000;txt='PERFECT';cls='perfect';if(mode==='hard'&&runes<4&&combo%6===0){runes++;renderRunes();if(runes===4){txt='RUNE AWAKENED';els.stage.classList.add('awakened')}}}else if(err<=windows.great){pts=700;txt='GREAT';cls='great'}else{pts=400;txt='GOOD';cls='good'}score+=pts+Math.min(combo,100)*5;flash(txt,cls);if(best.el){best.el.classList.add('hit');setTimeout(()=>best.el?.remove(),130)}updateHud()}
async function start(){reset();els.stage.focus();els.status.textContent=`${MODES[mode].label} · ${mode==='hard'?'연주 기억/룬 변주 활성':'정석 연주'}`;for(const n of ['3','2','1']){els.countdown.textContent=n;await new Promise(r=>setTimeout(r,450))}els.countdown.textContent='';try{els.song.playbackRate=playbackSpeed();await els.song.play()}catch(e){els.status.textContent='오디오 재생을 시작하지 못했습니다. 다시 눌러 주세요.';return}startAt=performance.now()+900;running=true;raf=requestAnimationFrame(frame)}
function finish(){running=false;cancelAnimationFrame(raf);els.song.pause();els.stage.classList.remove('improv');const acc=judged?Math.max(0,100-totalErr/judged/1.3):0;flash(acc>=95?'FULL GROOVE':acc>=85?'CLEAR':'FINISH',acc>=85?'perfect':'great');els.status.textContent=`완주 · ${hits}/${chart.length} HIT · ${acc.toFixed(2)}% · 룬 ${runes}/4${memory.length?` · 기억 ${memory.length}음`:''}`}
document.querySelectorAll('.difficulty').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;document.querySelectorAll('.difficulty').forEach(x=>x.classList.toggle('active',x===b));reset()}));els.start.addEventListener('click',start);document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(MODES[mode].keys.includes(k)){e.preventDefault();if(!e.repeat)press(k)}});reset();
})();